//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDAT.Modules.CompareCLangDefine.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDAT.Modules.CompareCLangDefine.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   追加定義 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddDefinition {
            get {
                return ResourceManager.GetString("AddDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更後定義 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AfterDefinition {
            get {
                return ResourceManager.GetString("AfterDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更後の値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AfterValue {
            get {
                return ResourceManager.GetString("AfterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更前定義 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BeforeDefinition {
            get {
                return ResourceManager.GetString("BeforeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更前の値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BeforeValue {
            get {
                return ResourceManager.GetString("BeforeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更定義 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeDefinition {
            get {
                return ResourceManager.GetString("ChangeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   比較 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除定義 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteDefinition {
            get {
                return ResourceManager.GetString("DeleteDefinition", resourceCulture);
            }
        }
    }
}
