//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDAT.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDAT.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Software Development Assistance Toolkit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重要なお知らせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportantNotice {
            get {
                return ResourceManager.GetString("ImportantNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用しているライブラリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LibrariesUsed {
            get {
                return ResourceManager.GetString("LibrariesUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライセンス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このソフトウェアはMITライセンスです。
        ///詳細は以下のURLを参照してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageAboutInfoLibrariesBody {
            get {
                return ResourceManager.GetString("MessageAboutInfoLibrariesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   致命的なエラーが発生しました｡
        ///このアプリケーションを終了します｡
        ///エラーの詳細な情報を表示しますか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFatalError {
            get {
                return ResourceManager.GetString("MessageFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このツールはソフトウェア開発に便利なツールを集めたツールキットです｡
        ///メニューからツールを選んでください｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageWelcomeBody {
            get {
                return ResourceManager.GetString("MessageWelcomeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ｢Software Development Assistance Toolkit｣へようこそ! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageWelcomeTitle {
            get {
                return ResourceManager.GetString("MessageWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
    }
}
